In the line below, write your first and last name.

Shirley Xu

In [0]:
import numpy as np
from numpy.random import *

In the empty code cell below, create a 5 x 3 matrix called ***mat1*** composed of random numbers taken from a Gaussian distribution. 

In [68]:
mat1 = np.random.randn (5,3)
mat1

array([[-1.55215231,  0.86622528, -0.65008866],
       [ 0.7212795 ,  0.69982874, -0.89283864],
       [-0.94013468,  0.71704516,  1.5109253 ],
       [-1.41364876, -2.03147894,  0.74036528],
       [-2.11914311,  2.42087922, -1.34614872]])

In the code cell below, create a 3 x 4 matrix called ***mat2*** where every element in the matrix is the value 1.

In [69]:
mat2 = np.ones([3,4])
print(mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In the code cell below, perform a matrix multiply between ***mat1*** and ***mat2*** and call the resulting matrix mat_mul.

In [70]:
mat1 = np.random.randn (5,3)
mat2 = np.ones([3,4])
mat_mul = np.matmul(mat1,mat2)
print(mat_mul)
print(mat_mul.shape)

[[-0.21359619 -0.21359619 -0.21359619 -0.21359619]
 [ 1.66653972  1.66653972  1.66653972  1.66653972]
 [-0.57410945 -0.57410945 -0.57410945 -0.57410945]
 [ 0.73194567  0.73194567  0.73194567  0.73194567]
 [ 2.19574232  2.19574232  2.19574232  2.19574232]]
(5, 4)


How many rows and columns should the matrix ***mat_mul*** have? Enter your answer in the line below.

5 x 4

Can ***mat1*** and ***mat2*** be added together, elementwise? Answer in the line below.

Yes

In the line below, print the value of ***mat1<sub>0,2</sub>***

In [0]:
mat1_02 = mat1[0,2]

In [72]:
print(mat1_02)

-0.5710006820135133


In the line below, change the value of ***mat1<sub>2,2</sub>*** to 0.3. Then, print ***mat1*** to show the change.

In [0]:
mat1[2,2] = 0.3

In [74]:
print (mat1[2,2])

0.3


In the line below, print the shape of ***mat2***.

In [75]:
print (mat2.shape)

(3, 4)


In the line below, add a value of 2.0 to every element in ***mat2***. Then print ***mat2*** to show the result.

In [0]:
mat2 = mat2 + 2

In [77]:
print (mat2)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In the line below, take the sum of each column of ***mat1*** and call the result ***mat1sum***. Then, print ***mat1sum*** and its shape.

In [78]:
mat1sum = np.sum(mat1,0)
print(mat1sum)
print(mat1sum.shape)

[ 3.54872725  4.77569695 -2.85207629]
(3,)


In the line below, write the shape you would expect if you transposed a 8 x 3 matrix.

3 x 8

In the line below, take the mean of ***mat1*** and call the result ***mat1mean***. Then, print ***mat1mean***.

In [79]:
mat1mean = np.mean(mat1)
print(mat1mean)

0.364823193519547


In the line below, create a variable called ***mat1row1*** which is the first row of ***mat1***. Then, print ***mat1row1*** and its shape.

In [80]:
mat1row1 = mat1[1,:]
print(mat1row1)
print(mat1row1.shape)

[ 0.58656543  1.48324797 -0.40327368]
(3,)


In the line below, create a variable called ***mat1row2*** which is the second row of ***mat1***. Then, print ***mat1row2*** and its shape.

In [81]:
mat1row2 = mat1[2,:]
print(mat1row2)
print(mat1row2.shape)

[0.55501263 0.23670374 0.3       ]
(3,)


In the line below, create a variable called ***mat1col1*** which is the first column of ***mat1***. Then, print ***mat1col1*** and its shape.

In [82]:
mat1col1 = mat1[:,1]
print(mat1col1)
print(mat1col1.shape)

[-0.66709188  1.48324797  0.23670374  2.59639807  1.12643904]
(5,)


In the line below, print the maximum value in ***mat1***, as well as the minimum value of ***mat1***.

In [83]:
mat1max = np.amax(mat1)
print(mat1max)
mat1min = np.amin(mat1)
print(mat1min)

2.596398073459466
-1.8948850015029086


In the line below, print the number of elements in ***mat1***.

In [84]:
mat1element = np.size(mat1)
print (mat1element)

15


In the line below, create a matrix of zeros called ***mat3*** with shape 4 x 4. Then print ***mat3***.

In [85]:
mat3 = np.zeros([4,4])
print(mat3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In the line below, create matrix of ones called ***mat4*** with shape 4 x 4. Then print ***mat4***.

In [86]:
mat4 = np.ones([4,4])
print(mat4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In the line below, add ***mat3*** and ***mat4*** elementwise and call the resulting matrix ***mat3_4***. Then print ***mat3_4***.

In [87]:
mat3_4 = mat3 + mat4
print(mat3_4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In the line below, multiply ***mat3*** by ***mat4*** elementwise and call the resulting matrix ***mat3_4mult*** and print it.

In [88]:
mat3_4mult = np.matmul(mat3,mat4)
print(mat3_4mult)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In the line below, create new matrix called ***mat5*** with shape 4 x 3 with random numbers from a normal distribution. Then print ***mat5***.

In [89]:
mat5 = np.random.randn (4,3)
print(mat5)

[[-0.52701571  0.15029225  0.75556633]
 [-1.11191347  0.95819176  1.94458975]
 [ 0.29263863 -0.26308333 -0.75184992]
 [ 1.40893121 -0.0394048   1.40532604]]


In the line below, write your answer to the following question: A matrix multiply can be performed between ***mat4*** and ***mat5*** in that order (True or False).

True

In the line below, write your answer to the following question: A matrix multiply can be performed between ***mat4*** and ***mat5*** if you transpose ***mat4*** (True or False).

True

In the line below, write your answer to the following question: A matrix multiply can be performed between ***mat5*** and ***mat4*** in that order (True or False).

False

In the line below, transpose ***mat4*** and perform a matrix multiply between ***mat4*** and ***mat5*** in that order and call the resulting matrix ***mat45mult***. Then, print the shape of the resulting matrix.

In [0]:
mat4 = mat4.transpose()

In [91]:
print(mat4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [92]:
mat45mult = np.matmul(mat4,mat5)
print(mat45mult.shape)

(4, 3)


To submit this assignment, click on File > Download as .ipynb and upload the downloaded notebook to the Homework1 folder on the class github. 