Neo Nguyen


In [0]:
import numpy as np
from numpy.random import *

In [7]:
mat1 = np.random.randn(5, 3)
print(mat1)

[[-1.3959257  -0.74971253 -1.31843938]
 [ 0.27182836 -1.2792101  -0.05391017]
 [ 0.3859277  -1.48293574  1.11770434]
 [ 0.21398448 -0.77061349  1.09746907]
 [ 0.85068571  0.54674282  0.32903976]]


In [8]:
mat2 = np.full((3,4), 1)
print mat2

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [9]:
mat_mul = np.matmul(mat1, mat2)
print(mat_mul)

[[-3.46407761 -3.46407761 -3.46407761 -3.46407761]
 [-1.06129191 -1.06129191 -1.06129191 -1.06129191]
 [ 0.0206963   0.0206963   0.0206963   0.0206963 ]
 [ 0.54084007  0.54084007  0.54084007  0.54084007]
 [ 1.7264683   1.7264683   1.7264683   1.7264683 ]]


4 columns, 5 rows

yes

In [10]:
print(mat1[0][2])

-1.318439375990972


In [11]:
mat1[2,2] = 0.3
print(mat1)

[[-1.3959257  -0.74971253 -1.31843938]
 [ 0.27182836 -1.2792101  -0.05391017]
 [ 0.3859277  -1.48293574  0.3       ]
 [ 0.21398448 -0.77061349  1.09746907]
 [ 0.85068571  0.54674282  0.32903976]]


In [14]:
print(mat2.shape)

(3, 4)


In [15]:
mat2 = mat2 + 2
print(mat2)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [16]:
mat1rowsum = [sum([row[i] for row in mat1]) for i in range(0,len(mat1[0]))]
print(mat1rowsum)

[0.32650055708157055, -3.735729033136489, 0.3541592873807809]


3 x 8

In [18]:
mat1mean = mat1.mean()
print(mat1mean)

-0.2036712792449425


In [20]:
mat1row1 = mat1[:][0]
print(mat1row1)
print(mat1row1.shape)

[-1.3959257  -0.74971253 -1.31843938]
(3,)


In [21]:
mat1row2 = mat1[:][1]
print(mat1row2)
print(mat1row2.shape)

[ 0.27182836 -1.2792101  -0.05391017]
(3,)


In [23]:
mat1col1 = mat1[0][:]
print(mat1col1)
print(mat1col1.shape)

[-1.3959257  -0.74971253 -1.31843938]
(3,)


In [24]:
print(np.amax(mat1))
print(np.amin(mat1))

1.0974690726704495
-1.4829357408941373


In [25]:
print(mat1.size)


15


In [26]:
mat3 = np.full((4,4),0)
print(mat3)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [28]:
mat4 = np.full((4,4),1)
print(mat4)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [29]:
mat3_4 = mat3+mat4
print(mat3_4)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [30]:
mat3_4mult = mat3 * mat4
print(mat3_4mult)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [31]:
mat5 = np.random.randn(4, 3)
print(mat5)

[[-0.92009474  0.7652972  -0.46637732]
 [-0.10282714 -1.03987683  2.03670499]
 [ 1.93341417 -0.09322134 -0.33868209]
 [-0.40003252  0.62473265 -0.4154799 ]]


True
True
False

In [33]:
mat4_transpose = mat4.transpose()
mat45mult = np.matmul(mat4,mat5)
print(mat45mult.shape)

(4, 3)
